export const types = {
    ADD_PROJECT: 'ADD_PROJECT',
    ADD_TO_PROJECT_TASK: 'ADD_TO_PROJECT_TASK',
    DELETE_PROJECT: 'DELETE_PROJECT',
    DELETE_PROJECT_TASK: 'DELETE_PROJECT_TASK',
    GET_PROJECTS: 'GET_PROJECTS',
    GET_CURRENT_PROJECT: 'GET_CURRENT_PROJECT',
    CHANGE_COLUMN_ORDER: 'CHANGE_COLUMN_ORDER',
    SET_COLUMNS: 'SET_COLUMNS',
    SET_TASKS: 'SET_TASKS',
    SET_CURRENT_PROJECT_ID: 'SET_CURRENT_PROJECT_ID',
    ADD_COLUMN: 'ADD_COLUMN',
    DELETE_COLUMN: 'DELETE_COLUMN',
    CHANGE_COLUMN_TITLE: 'CHANGE_COLUMN_TITLE',
    RESET_SELECTED_PROJECT: 'RESET_SELECTED_PROJECT'
};